layers: [
    {'in_d':64, 'out_d':100, 'activation': 'relu'},
    {'in_d':100, 'out_d':20, 'activation': 'relu'},
    # {'in_d':50, 'out_d':20, 'activation': 'relu'},
    {'in_d':20, 'out_d':10, 'activation': null},
  ]

train_val_test_split: [0.9, 0.1, 0.1]

epochs: 1000
learning_rate: 1.0e-4
log_n_steps: 1
log_run: True
use_n_datasamples: 10 # -1 for all